### PR TITLE
1103 fix line view bugs

### LINKED ISSUE #1103: Fix line / lineHeader view bugs
FE PR: https://github.com/HSLdevcom/jore-map-ui/pull/1184

Bugs:
* copy lineHeader button when disabled has wrong background
* toggling edit lineHeaders button shouldn't close currently opened lineHeader
* fix new lineView to work in firefox
* create new line -> try to create lineHeader (throws error)

### PR DESCRIPTION
**Pull request by Divinare**
Closes #1103 

Fixed issues:

* copy lineHeader button when disabled has wrong background
* create new line -> try to create lineHeader (throws error)
* double scrollbar bug in lineView with firefox.

Made a card for this: https://github.com/HSLdevcom/jore-map-ui/issues/1183
* switch back from stopAreaView with invalid properties -> save is possible when some fields are invalid (save button is green even though there are red validation messages)

* toggling edit lineHeaders button shouldn't close currently opened lineHeader
^ changed my mind. I think lineHeader form should be hidden when isEditing is false.

### CODE REVIEW

File: src/components/sidebar/lineView/LineHeaderTable.tsx [hunk 1]
```diff
@@ -73,10 +73,15 @@ class LineHeaderTable extends React.Component<ILineHeaderListProps, ILineHeaderS
     }
 
     private createNewLineHeader = () => {
-        const lastLineHeader = _.last(this.props.lineHeaderMassEditStore!.massEditLineHeaders)!
-            .lineHeader;
-        const defaultDate = new Date(lastLineHeader.endDate);
-        defaultDate.setDate(defaultDate.getDate() + 1);
+        const lastLineHeader = this.props.lineHeaderMassEditStore!.getLastLineHeader();
+        let defaultDate: Date;
```
Comment (ahjyrkia) [inline src/components/sidebar/lineView/LineHeaderTable.tsx]:
```
        let defaultDate: Date = new Date();

        if (lastLineHeader) {
            defaultDate = new Date(lastLineHeader.endDate);
            defaultDate.setDate(defaultDate.getDate() + 1);
        }
```

**Comment by ahjyrkia** [comment]
Reviewed
