### PR TITLE
706 fix issues with opening stores in react console

### LINKED ISSUE #706: Fix issues with opening stores in react console
Opening errorStore in react console crashes the application.

### PR DESCRIPTION
**Pull request by Divinare**
Closes #706

* Stores are a lot cleaner now. These errors pointed some out terrible code in our stores.

### CODE REVIEW

File: src/stores/networkStore.ts [hunk 1]
```diff
@@ -58,13 +58,10 @@ export class NetworkStore {
...
-    @computed
-    get visibleMapLayers(): MapLayer[] {
-        return this.visibleMapLayers;
-    }
-
     @computed
     get isMapLayersVisible(): boolean {
+        if (!this._visibleMapLayers) return false;
+
         return this._visibleMapLayers.length !== 0;
```
Comment (kronken) [inline src/stores/networkStore.ts]: return this._visibleMapLayers && this._visibleMapLayers.length !== 0;
