### PR TITLE
829 fix login bug

### LINKED ISSUE #829: Login says at first login "Tämä toimenpide on vanhentunut, ohjaamme sinut takaisin kirjautumissivulle"
I guess this is because of token getting old. Test if you can reproduce the bug with making token time 5 sec and logging in after a while.

### PR DESCRIPTION
**Pull request by Divinare**
Closes #829 

* test with both isLodingRequired true/false in BE / FE. Also put 5000 ms into server.ts cookie max age.

* initCodeList call is now in a bit odd place but wasn't able to get it work in init() func. But I think it should be fine where it is now

### CODE REVIEW

File: src/components/App.tsx [hunk 1]
```diff
@@ -64,11 +68,7 @@ class App extends React.Component<IAppProps, IAppState> {
     }
 
     componentWillMount() {
```
Comment (kronken) [inline src/components/App.tsx]: componentWillMount is legacy, and shouldn't really be used.

File: src/components/App.tsx [hunk 2]
```diff
@@ -80,20 +80,22 @@ class App extends React.Component<IAppProps, IAppState> {
         }
     }
 
-    private redirectToLogin = async () => {
+    private init = async () => {
```
Comment (kronken) [inline src/components/App.tsx]: Overall I find that the logic could be improved. It feels like a race condition that we call async method init, without awaiting it. What happens if init call takes longer than what it takes on our development machines. If init takes longer, then application will load as usually, but there will be errors, since we are not logged in. Then finally when the init() method completes, it will redirect the user to login page. I think this should be made so that the page is viewed right from the start, but App.tsx should only show a loading icon, as long as init() function is loading. When init function is done, we can then let the user access the app, or redirect the user to login page.

Comment (kronken) [reply src/components/App.tsx]: I know that your PR do not have anything to do with this thing, we could probably create an issue to fix this.

**Comment by Divinare** [comment]
Changed componentWillMount as componentDidMount. Also some minor refactoring + changed "Logging in... into Kirjaudutaan sisään"
