### PR TITLE
fixed inputContainer height, removed textContainer from inputContainer

### LINKED ISSUE #899: Make text field height as some static value when disabled

### PR DESCRIPTION
**Pull request by Divinare**
Closes #899

### CODE REVIEW

File: src/components/controls/TextContainer.tsx [hunk 1]
```diff
@@ -7,6 +7,7 @@ interface IInputProps {
     label: string | JSX.Element;
     value?: string | number | null | Date;
     darkerInputLabel?: boolean;
+    disabled?: boolean;
```
Comment (kronken) [inline src/components/controls/TextContainer.tsx]: Why does a TextContainer that is never editable, a prop named disabled?

Comment (Divinare) [reply src/components/controls/TextContainer.tsx]: Now TextContainer has always static height
