### PR TITLE
Fixed input container: moved validation to ViewFormBase

### LINKED ISSUE #756: InputContainer refactor: remove validations

### PR DESCRIPTION
**Pull request by Divinare**
Closes #756 

* merging this to #603 to help with double link creation bug
   * Making 2 links in a row doesn't work yet, will be fixed in #603

* input container is now more readable
* this also helps with some extra rendering issues, validate all input fields doens't trigger on change method calls as in previous version of inputContainer
* Node / stop validation is a bit different. Passing different validationModel depending on if validating node / stop. This won't work though if we add nodeValidationModel but it can be fixed later if nodeValidationModel is added

### CODE REVIEW

File: src/components/shared/inheritedComponents/ViewFormBase.tsx [hunk 1]
```diff
@@ -9,12 +10,35 @@ interface IViewFormBaseState {
...
+            .some(validatorResult => !validatorResult.isValid);
     }
 
-    protected markInvalidProperties = (property: string, isValid: boolean) => {
+    protected validateAllProperties = (validationModel: object, validationEntity: any) => {
+        this.setState({
+            invalidPropertiesMap: {},
+        });
+
+        for (const property of Object.keys(validationModel)) {
```
Comment (kronken) [inline src/components/shared/inheritedComponents/ViewFormBase.tsx]: Object.entries(validationModel).forEach(([key, value]) => {
// do something
});

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 2]
```diff
@@ -126,46 +131,43 @@ class NodeView extends ViewFormBase<INodeViewProps, INodeViewState> {
...
+        this.toggleIsEditingDisabled(
+            this.props.nodeStore!.resetChanges,
+        );
+    }
+
+    private _validateAllProperties = (nodeType: NodeType) => {
+        const node = this.props.nodeStore!.node;
+        if (nodeType === NodeType.STOP) {
+            this.validateAllProperties(stopValidatorModel, node.stop);
+        } else {
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: Add task to validate node.

**Comment by Divinare** [comment]
Created card #758 for validating node & stop properties

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 3]
```diff
@@ -126,46 +131,43 @@ class NodeView extends ViewFormBase<INodeViewProps, INodeViewState> {
...
-        property: NodeLocationType,
-    ) => (
-        value: any, validationResult?: IValidationResult,
-    ) => {
+    private onNodeGeometryChange = (property: NodeLocationType) => (value: any) => {
         this.props.nodeStore!.updateNodeGeometry(property, value);
-        if (validationResult) {
-            this.markInvalidProperties(property, validationResult!.isValid);
-        }
+        this.validateProperty({}, property, value);
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: Add todo to describe {}

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 4]
```diff
@@ -126,46 +131,43 @@ class NodeView extends ViewFormBase<INodeViewProps, INodeViewState> {
...
 
-    private onStopChange =
-        (property: string) => (value: any, validationResult?: IValidationResult) => {
-            this.props.nodeStore!.updateStop(property, value);
-            if (validationResult) {
-                this.markInvalidProperties(property, validationResult!.isValid);
-            }
+    private onNodePropertiesChange = (property: string) => (value: any) => {
+        this.props.nodeStore!.updateNode(property, value);
+        this.validateProperty({}, property, value);
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: Add todo

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 5]
```diff
@@ -126,46 +131,43 @@ class NodeView extends ViewFormBase<INodeViewProps, INodeViewState> {
...
+        if (property === 'type') {
+            this._validateAllProperties(value);
         }
+    }
 
-    private toggleIsEditingEnabled = () => {
-        this.toggleIsEditingDisabled(
-            this.props.nodeStore!.resetChanges,
-        );
+    private onStopPropertiesChange = (property: string) => (value: any) => {
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: onStopPropertyChange? we are modifying one property

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 6]
```diff
@@ -126,46 +131,43 @@ class NodeView extends ViewFormBase<INodeViewProps, INodeViewState> {
...
+        this.validateProperty({}, property, value);
     }
 
-    private onStopChange =
-        (property: string) => (value: any, validationResult?: IValidationResult) => {
-            this.props.nodeStore!.updateStop(property, value);
-            if (validationResult) {
-                this.markInvalidProperties(property, validationResult!.isValid);
-            }
+    private onNodePropertiesChange = (property: string) => (value: any) => {
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: onNodePropertyChange? we are modifying one property

File: src/components/sidebar/nodeView/StopForm.tsx [hunk 7]
```diff
@@ -1,20 +1,19 @@
...
 import municipalityCodeList from '~/codeLists/municipalityCodeList';
 import { Dropdown } from '~/components/controls';
 import SidebarHeader from '../SidebarHeader';
 import * as s from './stopForm.scss';
 
 interface IStopFormProps {
     stop: IStop;
-    onChange: (property: string) => (value: any, validationResult?: IValidationResult) => void;
     isEditingDisabled: boolean;
+    onChange: Function;
```
Comment (kronken) [inline src/components/sidebar/nodeView/StopForm.tsx]: typings for Function

File: src/components/sidebar/routePathView/routePathInfoTab/RoutePathForm.tsx [hunk 8]
```diff
@@ -22,20 +21,13 @@ interface IRoutePathFormProps {
     isEditingDisabled: boolean;
     routePath: IRoutePath;
     isNewRoutePath: boolean;
-    markInvalidProperties: (property: string, isValid: boolean) => void;
+    onChange: Function;
```
Comment (kronken) [inline src/components/sidebar/routePathView/routePathInfoTab/RoutePathForm.tsx]: typings for Function

File: src/components/sidebar/routePathView/routePathInfoTab/RoutePathInfoTab.tsx [hunk 9]
```diff
@@ -14,8 +14,9 @@ interface IRoutePathInfoTabProps {
     isEditingDisabled: boolean;
     routePathStore?: RoutePathStore;
     routePath: IRoutePath;
-    markInvalidProperties: (property: string, isValid: boolean) => void;
     isNewRoutePath: boolean;
+    onChange: Function;
```
Comment (kronken) [inline src/components/sidebar/routePathView/routePathInfoTab/RoutePathInfoTab.tsx]: typings for Function

File: src/models/IStop.ts [hunk 10]
```diff
@@ -2,7 +2,7 @@ export default interface IStop {
     nodeId: string;
     municipality: string;
     nameFi: string;
-    nameSe: string;
+    nameSe: string; // TODO: rename as nameSw
```
Comment (kronken) [inline src/models/IStop.ts]: Standard swedish should be Sv, https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

File: src/validation/models/stopValidatorModel.ts [hunk 11]
```diff
@@ -0,0 +1,10 @@
+const nameRule = 'required|min:1|max:20|string'; // TODO: These are just made up
```
Comment (kronken) [inline src/validation/models/stopValidatorModel.ts]: Why was this file renamed?

Comment (Divinare) [reply src/validation/models/stopValidatorModel.ts]: Because it really is stop validationModel, all validations are for stop properties

File: src/components/sidebar/nodeView/NodeView.tsx (hunk 2 above)
Comment (Divinare) [reply src/components/sidebar/nodeView/NodeView.tsx]: #758

File: src/models/IStop.ts (hunk 10 above)
Comment (Divinare) [reply src/models/IStop.ts]: Hmm, then our routePathProperties should be renamed too.. they end with xxxSw

Comment (kronken) [reply src/models/IStop.ts]: Hmm, I have no difference which way we go, both Se, Sw and Sv goes well for me. But it would probably be good to be consistent. Personally I think Sw sounds most describable, but Sv is the standard. Which way should we go?

File: src/validation/models/stopValidatorModel.ts (hunk 11 above)
Comment (kronken) [reply src/validation/models/stopValidatorModel.ts]: you renamed the file from stopValidationModel to stopValidatorModel. All other models have validation not validator.

File: src/components/shared/inheritedComponents/ViewFormBase.tsx (hunk 1 above)
Comment (Divinare) [reply src/components/shared/inheritedComponents/ViewFormBase.tsx]: Looping through entries now. ValidateProperty now takes validatorRule instead of validationModel.

File: src/components/sidebar/nodeView/NodeView.tsx (hunk 5 above)
Comment (Divinare) [reply src/components/sidebar/nodeView/NodeView.tsx]: We are modifiying multiple properties. This function is just used once

Comment (Divinare) [reply src/components/sidebar/nodeView/NodeView.tsx]: (and we have onNodePropertiesChange)

Comment (Divinare) [reply src/components/sidebar/nodeView/NodeView.tsx]: Or hmm, maybe I see your point. Changing one property at once. Then also onNodePropertiesChange should be renamed to onNodePropertyChange

File: src/models/IStop.ts (hunk 10 above)
Comment (Divinare) [reply src/models/IStop.ts]: I would go with Sw which is closer to "Swedish", I don't like "nameSv" that much

File: src/validation/models/stopValidatorModel.ts (hunk 11 above)
Comment (Divinare) [reply src/validation/models/stopValidatorModel.ts]: Fixed now, my bad

**Comment by Divinare** [comment]
Review fixes done ^

File: src/models/IStop.ts (hunk 10 above)
Comment (kronken) [reply src/models/IStop.ts]: okay, lets go with Sw
