### PR TITLE
208 select node route fix

### LINKED ISSUE #208: Node index page part 1 - nodeService & node/:id
* if user selects a node, go to /node/:id/?...

### PR DESCRIPTION
**Pull request by Divinare**
Closes #208 

Fetching routes at node/:id bug will be fixed here: https://github.com/HSLdevcom/jore-map-ui/issues/240

### CODE REVIEW

**Comment by Divinare** [comment]
Pending, implementing targetId parsing from url.

**Comment by Divinare** [comment]
You can review this now

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 1]
```diff
@@ -63,76 +90,114 @@ class NodeView extends React.Component
...
+                        {this.props.nodeStore!.selectedNodeId ? (
+                            <div>Solmua {this.props.nodeStore!.selectedNodeId} ei löytynyt.</div>
+                        ) : (
+                            <div>Solmua ei löytynyt.</div>
+                        )}
+                    </div>
+                ) : (
+                <div>
+                    <ViewHeader
+                        header={`Solmu ${this.capitalizeFirstLetter(node.jore_solkuka)}`}
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: jore_solkuka is the name of the user that last modified the node. A better alternative would be: solmu.pysakkiBySoltunnus.pysnimi or solmu.pysakkiBySoltunnus.pysnimir.

File: src/components/map/layers/PopupLayer.tsx [hunk 2]
```diff
@@ -31,12 +31,10 @@ class PopupLayer extends Component<PopupLayerProps> {
             const node = this.props.popupStore!.popupNode as INode;
 
             const openNode = () => {
-                // TODO deal fetching nodeId this in the endpoint
-                this.props.sidebarStore!.setOpenNodeId(node.id);
```
Comment (kronken) [inline src/components/map/layers/PopupLayer.tsx]: I don't quite understand the Todo, what does "nodeId this in the endpoint" mean?

File: src/components/sidebar/nodeView/NodeView.tsx [hunk 3]
```diff
@@ -63,76 +90,114 @@ class NodeView extends React.Component
...
+                            s.stopInUseRow,
+                        )}
+                    >
+                        <div className={s.rowElement}>
+                            Pysäkki käytössä
+                        </div>
+                        <ToggleSwitch
+                            onClick={this.toggleStopInUse}
+                            value={true}
+                            type={TransitType.BUS}
```
Comment (kronken) [inline src/components/sidebar/nodeView/NodeView.tsx]: This type prop is actually not used in ToggleSwitch (atleast from what I found). So, we could probably remove it instead of setting a value that is just set without any reason.

File: src/services/nodeService.ts [hunk 4]
```diff
@@ -0,0 +1,41 @@
+import gql from 'graphql-tag';
+import { ApolloQueryResult } from 'apollo-client';
+import apolloClient from '../util/ApolloClient';
+import { INode } from '../models';
+import notificationStore from '../stores/notificationStore';
+import NotificationType from '../enums/notificationType';
+import NodeFactory from '../factories/nodeFactory';
+
+export default class NodeService {
+    public static async fetchNode(nodeId: string): Promise<INode | null> {
```
Comment (kronken) [inline src/services/nodeService.ts]: Do we really need this wrapper function?

File: src/components/map/layers/PopupLayer.tsx (hunk 2 above)
Comment (Divinare) [reply src/components/map/layers/PopupLayer.tsx]: I guess it was written by VV and it means to read nodeId from url params instead of adding it to store when clicking "Avaa solmu" from popup

File: src/models/INode.ts [hunk 5]
```diff
@@ -3,8 +3,11 @@ import INodeStop from './INodeStop';
...
 
 export default interface INode {
-    id: number;
+    id: string;
     stop: INodeStop|null;
     type: NodeType;
     coordinates: ICoordinate;
+    jore_mittpvm: string;
+    jore_solviimpvm: string;
+    jore_solkuka: string;
```
[the remark this answers is not in the document]
Comment (Divinare) [reply src/models/INode.ts]: MeasurementDate
ModifiedOn
ModifiedBy

File: src/components/sidebar/nodeView/NodeView.tsx (hunk 3 above)
Comment (Divinare) [reply src/components/sidebar/nodeView/NodeView.tsx]: This was already done like this master but I can refactor it out.
