### PR TITLE
662 error param to error store

### LINKED ISSUE #662: Add error param to errorStore's addError
* Also: should try catch be done inside services?

Make errorStore to print error + stack trace to the console
```
    @action
    public addMessage(message: string, error?: Error) {
        this._errors.push(message);
        /* tslint:disable no-console */
        if(error) console.error(error);
        /* tslint:enable no-console */
    }
```

* Also search for ".catch(", we now have catch (ex) and catch (err) --> pick 1 for consistency

### PR DESCRIPTION
**Pull request by kronken**
Closes #662

### CODE REVIEW

File: src/models/IError.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export default interface IError extends Error {
+    errorCode?: number;
```
Comment (Divinare) [inline src/models/IError.ts]: Forgot to add these message & name properties?

File: src/components/map/tools/ExtendRoutePathTool.ts [hunk 2]
```diff
@@ -39,7 +39,8 @@ class ExtendRoutePathTool implements BaseTool {
             RoutePathStore!.setNeighborToAddType(queryResult!.neighborToAddType);
 
         } catch (ex) {
-            ErrorStore.addError((ex as Error).message);
+            ErrorStore.addError(
+                'Unable to process network node click using ExtendRoutePathTool', ex);
```
Comment (Divinare) [inline src/components/map/tools/ExtendRoutePathTool.ts]: Use finnish

File: src/stores/errorStore.ts [hunk 3]
```diff
@@ -22,14 +23,14 @@ export class ErrorStore {
     }
 
     @action
-    public addError(message: string, error?: Error) {
+    public addError(message: string, error?: IError) {
```
Comment (Divinare) [inline src/stores/errorStore.ts]: Hmm, error is always given as param. I would change: error? -> error, error as required param

File: src/util/ApiClient.ts [hunk 4]
```diff
@@ -73,12 +69,13 @@ class ApiClient {
...
             }
             error = {
+                name: 'Failed to fetch',
                 errorCode: response.status,
                 message: response.statusText,
             };
         } catch (err) {
-            console.log(err); // tslint:disable-line no-console
             error = {
+                name: 'Connectivity error',
```
Comment (Divinare) [inline src/util/ApiClient.ts]: Name field is only being used within tests (if i'm not blind) so why add name property? In tests, you can just compare error message

File: src/stores/__tests__/errorStore.test.ts [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+
+        expect(errorStore.errorCount).toEqual(1);
+
+        const error = errorStore.pop();
+
+        expect(error).toEqual(errorMessage);
+        expect(errorStore.errorCount).toEqual(0);
+    });
+
+    it('Adds one error with exception to error store', () => {
```
Comment (Divinare) [inline src/stores/__tests__/errorStore.test.ts]: I would change name of this test as "Adds one error to error store" if error is made as required param

File: src/stores/__tests__/errorStore.test.ts [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+        // tslint:disable:no-console
+        // Mocks console.error
+        const consoleError = console.error;
+        global.console.error = jest.fn();
+
+        const errorStore = new ErrorStore;
+        const errorMessage = 'This is a test error';
+        const exceptionMessage = 'This is a test exception message';
```
Comment (Divinare) [inline src/stores/__tests__/errorStore.test.ts]: Hmm, exception & error... both mean the same. errorMessage1, errorMessage2? I wouldn't use exception word

See my comment @ this card's description:
Also search for ".catch(", we now have catch (ex) and catch (err) --> pick 1 for consistency

There is still one catch(err) ...

I would use error everywhere (addError, errorMessage, catch(err), etc)

File: src/models/IError.ts (hunk 1 above)
Comment (kronken) [reply src/models/IError.ts]: IError extends Error, message and name properties are included in Error interface

File: src/components/map/tools/ExtendRoutePathTool.ts (hunk 2 above)
Comment (kronken) [reply src/components/map/tools/ExtendRoutePathTool.ts]: oh

Comment (kronken) [reply src/components/map/tools/ExtendRoutePathTool.ts]: true dat

File: src/stores/errorStore.ts (hunk 3 above)
Comment (kronken) [reply src/stores/errorStore.ts]: Hmm, really? That would remove the possibility for us to create simple error notification.
Instead we would always need to come up with an exception.

File: src/util/ApiClient.ts (hunk 4 above)
Comment (kronken) [reply src/util/ApiClient.ts]: Name is a default property of the Typescript Error interface

File: src/stores/__tests__/errorStore.test.ts (hunk 6 above)
Comment (kronken) [reply src/stores/__tests__/errorStore.test.ts]: Error does not mean the same thing as an exception. Error means a generic issue that has come up. We could basically write 'Lost contact with the server', without ever throwing an exception. Exception is a standard for throwing and catching errors.

File: src/stores/errorStore.ts (hunk 3 above)
Comment (kronken) [reply src/stores/errorStore.ts]: Check https://github.com/HSLdevcom/jore-map-ui/blob/20c626455a28815a44765c6a97e11a1cb27c6656/src/services/routePathLinkService.ts#L79

File: src/stores/__tests__/errorStore.test.ts (hunk 5 above)
Comment (kronken) [reply src/stores/__tests__/errorStore.test.ts]: I would not make error a mandatory property, we currently have use cases where we show error messages, where it would be unneccessary to add an exception:
https://github.com/HSLdevcom/jore-map-ui/blob/20c626455a28815a44765c6a97e11a1cb27c6656/src/services/routePathLinkService.ts#L79

File: src/components/map/tools/ExtendRoutePathTool.ts (hunk 2 above)
Comment (kronken) [reply src/components/map/tools/ExtendRoutePathTool.ts]: Do you have a available translation for: Unable to process network node click using ExtendRoutePathTool

File: src/models/IError.ts (hunk 1 above)
Comment (Divinare) [reply src/models/IError.ts]: Ah I see

File: src/components/map/tools/ExtendRoutePathTool.ts (hunk 2 above)
Comment (Divinare) [reply src/components/map/tools/ExtendRoutePathTool.ts]: Perhaps `Solmusta (soltunnus: ${properties.soltunnus} alkavien linkkien haku epäonnistui`

But hmm, seems like routePathLinkServie already does a try catch... maybe we should remove it if we decided to try catch outside of service

File: src/stores/__tests__/errorStore.test.ts (hunk 6 above)
Comment (Divinare) [reply src/stores/__tests__/errorStore.test.ts]: https://stackoverflow.com/questions/16142583/whats-the-difference-between-error-and-exception-in-javascript

says: Behind the scenes, the browsers use the same window.Error constructor. An Exception is an Error instance with a name and message that contain "Exception"

So okay that is an exception if it has name & message fields.

```
        const errorStore = new ErrorStore;
        const errorMessage = 'This is a test error';
        const exception: Error = {
            message: 'This is a test exception message',
            name: 'Test exception',
        };
        errorStore.addError(errorMessage, exception);
```

Comment (Divinare) [reply src/stores/__tests__/errorStore.test.ts]: Based on that link, we should maybe use catch (e) because we don't know if its an exception or error
