### PR TITLE
fixed datedelta format for RouteShow

### LINKED ISSUE #381: Remove alk.pvm and Voim.ast from routes list

### PR DESCRIPTION
**Pull request by neodyymi**
fixes #381

### CODE REVIEW

File: src/components/sidebar/routesView/RouteShow.tsx [hunk 1]
```diff
@@ -103,26 +103,21 @@ class RouteShow extends React.Component<IRouteShowProps> {
...
                                 </div>
-                            </div>
-                            <div className={s.routePathDate}>
-                                <div
-                                    className={(isWithinTimeSpan) ?
-                                    classNames(s.flexColumn, s.routePathDate, s.highlight) :
-                                    classNames(s.flexColumn, s.routePathDate)}
-                                >
-                                    {'Voim.ast:'}
+                                <div className={s.flexColumn}>
```
Comment (Divinare) [inline src/components/sidebar/routesView/RouteShow.tsx]: Don't use flex column wrapper here. Also remove it from those other 2 places as well.

File: src/components/sidebar/routesView/routeShow.scss [hunk 2]
```diff
@@ -56,6 +56,12 @@
                 font-size: $smallFontSize;
                 padding-left: 10px;
                 padding-top: 2px;
+                display: flex;
+
+                div:nth-child(2) {
+                    min-width: 20px;
+                    text-align: center;
+                }
```
Comment (Divinare) [inline src/components/sidebar/routesView/routeShow.scss]: Would using a className like ".separator" plus padding left 10px, padding right 10px be more readable? I think so. Now when just watching this css, it is hard to see what this is used for

File: src/components/sidebar/routesView/RouteShow.tsx [hunk 3]
```diff
@@ -103,26 +103,21 @@ class RouteShow extends React.Component<IRouteShowProps> {
                             {`${routePath.originFi}-${routePath.destinationFi}`}
                         </div>
                         <div className={s.flexInnerRow}>
```
Comment (Divinare) [inline src/components/sidebar/routesView/RouteShow.tsx]: flexInnerRow className needed?

File: src/components/sidebar/routesView/RouteShow.tsx (hunk 1 above)
Comment (neodyymi) [reply src/components/sidebar/routesView/RouteShow.tsx]: Removed many extra classes

File: src/components/sidebar/routesView/routeShow.scss (hunk 2 above)
Comment (neodyymi) [reply src/components/sidebar/routesView/routeShow.scss]: Changed this to use class instead of pseudoclass

File: src/components/sidebar/routesView/RouteShow.tsx (hunk 3 above)
Comment (neodyymi) [reply src/components/sidebar/routesView/RouteShow.tsx]: Removed
