### PR TITLE
721 validation bud when switching node type 2

### LINKED ISSUE #721: Switching nodeView's nodeType prevents saving if validations were broken
Steps:
1. Open node that is a stop
1. Change some field so that validation fails
1. Change nodeType to crossroad
--> save button is grey

This seems to be fixed in master, I can't get this problem to occur. NO PR.

### PR DESCRIPTION
**Pull request by Divinare**
Closes #721 

old PR: https://github.com/HSLdevcom/jore-map-ui/pull/800

### CODE REVIEW

File: src/stores/nodeStore.ts [hunk 1]
```diff
@@ -146,6 +152,11 @@ export class NodeStore {
         };
     }
 
+    @action
+    public setIsFormValid = (isStopFormValid: boolean) => {
```
Comment (kronken) [inline src/stores/nodeStore.ts]: setIsStopFormValid

File: src/components/sidebar/nodeView/StopForm.tsx [hunk 2]
```diff
@@ -9,223 +13,272 @@ import * as s from './stopForm.scss';
...
-                    />
-                </div>
-                </div>
+interface IStopFormState {
+    isLoading: boolean;
+    invalidPropertiesMap: object;
+    isEditingDisabled: boolean;
+}
+
+@inject('dialogStore', 'nodeStore', 'mapStore', 'errorStore')
```
Comment (kronken) [inline src/components/sidebar/nodeView/StopForm.tsx]: only nodeStore is used

File: src/components/sidebar/nodeView/StopForm.tsx [hunk 3]
```diff
@@ -9,223 +13,272 @@ import * as s from './stopForm.scss';
...
+    private _validateAllProperties = () => {
+        const node = this.props.nodeStore!.node;
+        if (!node) return;
+        const stop = node.stop;
+        this.validateAllProperties(stopValidationModel, stop);
+        const isStopFormValid = this.isFormValid();
+        this.props.nodeStore!.setIsFormValid(isStopFormValid);
+    }
+
+    private onStopPropertyChange = (property: string) => (value: any) => {
```
Comment (kronken) [inline src/components/sidebar/nodeView/StopForm.tsx]: constistent naming, why does _validateAllProperties start with _, but onStopPropertyChange not?

File: src/components/sidebar/nodeView/StopForm.tsx [hunk 4]
```diff
@@ -9,223 +13,272 @@ import * as s from './stopForm.scss';
...
-                        onChange={onChange('municipality')}
-                        codeList={municipalityCodeList}
-                        selected={stop.municipality}
-                        disabled={isEditingDisabled}
-                        label='KUNTA'
-                    />
-                </div>
-                </div>
+interface IStopFormState {
+    isLoading: boolean;
```
Comment (kronken) [inline src/components/sidebar/nodeView/StopForm.tsx]: Add comment that they are not used?

File: src/components/sidebar/nodeView/StopForm.tsx (hunk 3 above)
Comment (Divinare) [reply src/components/sidebar/nodeView/StopForm.tsx]: There are two validateAllProperties functions, one in IViewModel, one here so thats why I added _

Not using _ at onStopPropertyChange because that is not our convention

Comment (kronken) [reply src/components/sidebar/nodeView/StopForm.tsx]: validateStop?
