### PR TITLE
fixed handling measured position missing in backend

### LINKED ISSUE #252: Use new dump data (pysäkkialue etc) in postgres and show it in graphql

### PR DESCRIPTION
**Pull request by neodyymi**
Changes mostly in backend - Check gitlab merge request 7
closes #252

### CODE REVIEW

File: src/factories/nodeFactory.ts [hunk 1]
```diff
@@ -4,7 +4,8 @@ import NodeStopFactory from './nodeStopFactory';
 
 class NodeFactory {
     public static createNode = (node: any): INode => {
-        const coordinateList = JSON.parse(node.geojson);
+        const coordinateList = // Use less accurate location if measured location is missing.
+            JSON.parse(node.geojson ? node.geojson : node.geojsonDisp);
```
Comment (Divinare) [inline src/factories/nodeFactory.ts]: display
