### PR TITLE
670 fix optional field validation

### LINKED ISSUE #670: Create new routePath optional field validation broken, fix routePath view initialization
* Open any route, click "Luo uusi reitinsuunta"
* Fill required fields "LÄHTÖPAIKKA SUOMEKSI" "LÄHTÖPAIKKA RUOTSIKSI"
--> optional field seems to be required but save button can still be clicked

Also to fix:
* fix poikkeusreittin being null causing error

And fix in new routePath form:
* hide edit button
* make save form appear as editable (as default)

### PR DESCRIPTION
**Pull request by Divinare**
Closes #670

Check from card description what was done here.

Made new card #677, didn't want to do it here because it seemed a bit confusing and didn't quite relate to this task

Review commit by commit.

Test inputContainer properly, try to find if there are any bugs left

### CODE REVIEW

**Comment by Divinare** [comment]
Accidentally pushed changes from #672 to here so I had to remove that commit from here. Thats why it says "Divinare force-pushed..."

File: src/components/sidebar/InputContainer.tsx [hunk 1]
```diff
@@ -110,6 +83,10 @@ class InputContainer extends React.Component<IInputProps, IInputState> {
                 />
             );
         }
+        const value = (typeof this.props.value === 'string'
```
Comment (kronken) [inline src/components/sidebar/InputContainer.tsx]: What is this supposed to do?

File: src/components/sidebar/InputContainer.tsx [hunk 2]
```diff
@@ -1,18 +1,18 @@
 import React from 'react';
 import classnames from 'classnames';
-import moment from 'moment';
 import FormValidator, { IValidationResult } from '../../validation/FormValidator';
 import DatePicker from '../controls/DatePicker';
 import * as s from './inputContainer.scss';
+import TextContainer from './TextContainer';
```
Comment (kronken) [inline src/components/sidebar/InputContainer.tsx]: import order

File: src/components/sidebar/TextContainer.tsx [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+
+const x = (props: IInputProps) => (
+    <div className={s.formItem}>
+        <div className={s.inputLabel}>
+            {props.label}
+        </div>
+        {
+            props.value instanceof Date ?
+                moment(props.value!).format('DD.MM.YYYY') :
+                props.value ?
```
[the remark this answers is not in the document]
Comment (Divinare) [reply src/components/sidebar/TextContainer.tsx]: This was ok imo before but now fixed a bit

File: src/components/sidebar/InputContainer.tsx (hunk 1 above)
Comment (Divinare) [reply src/components/sidebar/InputContainer.tsx]: This fixed that strange bug where empty field change caused some console error. I guess it was because before the value was casted as string / number, now it doesn't do that.

Code that caused that strange console error:
value={this.props.value !== null ? (this.props.value as string | number) : ''}

**Comment by Divinare** [comment]
Review fixes done
